proxy-providers:
  Residential ip:
    type: http  
    url: "http://proxy.urekagodesk.tech:1987/proxy-providers"
    interval: 3600  
    health-check:
      enable: true  
      interval: 600  
      url: http://www.gstatic.com/generate_204
    header: 
      Authorization:
        # Input your ID below. For example: if your ID is UGV0ZXI6cGFzc3dvcmQ=, 
        # the filled result should be "Basic UGV0ZXI6cGFzc3dvcmQ="
        - "Basic Your_ID"  

# Specify the UA when downloading the subscription
# global-ua: clash

# Global configuration
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
ipv6: false
allow-lan: true
unified-delay: true
tcp-concurrent: true

# Control panel
external-controller: 0.0.0.0:9090
secret: "password"
external-ui: "/etc/mihomo/run/ui"
external-ui-name: urekago-board
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# Match processes always/strict/off
find-process-mode: strict
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

# Policy group selection and fakeip cache
profile:
  store-selected: true
  store-fake-ip: true

# Proxy mode
mode: global
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

# DNS module
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  # Mode switching redir-host / fake-ip
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  # Mode switching whitelist/blacklist 
  # The blacklist mode means that if the match is successful, Fake-IP will not be returned. In the whitelist mode, Fake-IP will only be returned if the match is successful.
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "+.services.googleapis.cn"
    - "+.xn--ngstr-lra8j.com"
    - "time.*.com"
    - "+.pool.ntp.org"
    - "+.ntp.tencent.com"
    - "+.ntp1.aliyun.com"
    - "+.ntp.ntsc.ac.cn"
    - "+.cn.ntp.org.cn"
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 8.8.8.8
    - 119.29.29.29
  nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 223.5.5.5
    - 119.29.29.29

proxy-groups:
  - {name: GLOBAL, type: select, use: [Residential ip], proxies: [DIRECT]}